#!/bin/sh

echo "Enter the number of terms you want in the Fibonacci series: "
read n

a=0
b=1
echo "The Fibonacci series for $n terms is: "
echo $a
echo $b

for (( i=2; i<n; i++ ))
do
c=$((a+b))
echo $c
a=$b
b=$c
done

echo "Done!"
