#!/bin/bash

This script calculates the factorial of a given number
read -p "Enter a number: " n # prompting user to enter a number to calculate factorial

factorial=1 # initializing the factorial to 1

loop to calculate the factorial
for ((i=1;i<=n;i++))
do
factorial=$((factorial*i))
done

echo "Factorial of $n is $factorial" # displaying the calculated factorial
