#!/bin/bash
echo "Enter a number: "
read num
len=${#num}
sum=0

for((i=0;i<len;i++))
do
digit=$(( ${num:$i:1} ** $len ))
sum=$(( $sum + $digit ))
done

if [ $sum -eq $num ]
then
echo "$num is an Armstrong number"
else
echo "$num is not an Armstrong number"
fi
